name: bingo

on:

  # Workflow to update bingo files when a bingo tool dependency is
  # changed. Intended for use with automated tools like renovate.
  #
  # name: bingo
  # on:
  #   pull_request:
  #     branches:
  #       - main
  #     paths:
  #       - '.bingo/*.mod'
  # permissions:
  #   contents: write # Required to push changes back to the PR branch.
  # jobs:
  #   bingo:
  #     uses: ntnn/actions/.github/workflows/bingo.yaml@main

  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: stable
        description: 'go-version input for setup-go.'
      go-version-file:
        required: false
        type: string
        default: ''
        description: 'go-version-file input for setup-go.'
      bingo-command:
        required: false
        type: string
        default: 'go run github.com/bwplotka/bingo@latest'
        description: 'Command to run bingo, could be replaced with e.g. `go tool bingo` if bingo is configured as a go tool.'
      commit-message:
        required: false
        type: string
        default: 'chore(deps): update bingo files'
        description: 'Commit message for the changes made by bingo.'
      git-user:
        required: false
        type: string
        default: ${{ github.repository_owner }}
        description: 'Git user name to use for the commit.'
      git-email:
        required: false
        type: string
        default: ${{ github.repository_owner }}@users.noreply.github.com
        description: 'Git email to use for the commit.'
      push-ref:
        required: false
        type: string
        default: ${{ github.head_ref }}
        description: 'Git ref to push the changes to, defaults to the PR head ref.'

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}

      - run: ${{ inputs.bingo-command }} get

      - run: echo "changes=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"
        id: changes
      - if: steps.changes.outputs.changes != '0'
        run: |
          git config --local user.name "${{ input.git-user }}"
          git config --local user.email "${{ input.git-email }}"
          git add .bingo/*
          git commit -m "${{ inputs.commit-message }}"
          git push origin HEAD:${{ input.push-ref }}
